#!/bin/sh

MAX_NUM_RSYNC=10
REJECT_MSG="Denied by Script"

function if_accept()
{
  num=`ps aux | grep rsync | wc -l`
  if test $num -gt $MAX_NUM_RSYNC
  then
    echo "Rejected current num=$num"
  else
    $SSH_ORIGINAL_COMMAND
  fi
}

case "$SSH_ORIGINAL_COMMAND" in
*\&*)
echo $REJECT_MSG
;;
*\(*)
echo $REJECT_MSG
;;
*\{*)
echo $REJECT_MSG
;;
*\;*)
echo $REJECT_MSG
;;
*\<*) 
echo $REJECT_MSG 
;; 
*\`*) 
echo $REJECT_MSG 
;; 
*\|*) 
echo $REJECT_MSG 
;; 
rsync\ --server*) 
if_accept
;; 
*) 
echo $REJECT_MSG 
;; 
esac 
